#version: 2.1
#orbs:
#  node: circleci/node@1.1
#jobs:
#  build:
#    executor:
#      name: node/default
#      tag: '10.4'
#    steps:
#      - checkout
#      - node/with-cache:
#          steps:
#            - run: npm install
#      - run: npm run test
#      - run: npm run build
#  workflows:
#    version: 2
#    test_and_deploy:
#      jobs:
#        - test
#        - build
#        - deploy:
#           # Only deploy if tests pass
#           requires:
#             - test
#           # Only deploy the master branch
#           filters:
#             branches:
#               only: production
